import { createFileRoute } from "@tanstack/react-router";
import { onAuthStateChanged, type User } from "firebase/auth";
import {
  Download,
  FileText,
  Loader2,
  RefreshCw,
} from "lucide-react";
import { useEffect, useState } from "react";

import { AppLayout } from "@/components/AppLayout";
import { auth } from "@/lib/firebase";

const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL ||
  "http://127.0.0.1:8000";

type AnalysisHistoryItem = {
  job_id: string;
  status: string;
  completed_at?: string | null;
  started_at?: string | null;
  dataset_name?: string | null;
  file_size?: number | null;
  owner_uid?: string | null;
  report_available?: boolean;
};

type AnalysisHistoryResponse = {
  jobs?: AnalysisHistoryItem[];
};

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — ImmunoXAI" },
      {
        name: "description",
        content:
          "Download PDF reports generated from your completed IMMUNO-XAI analyses.",
      },
    ],
  }),
  component: Reports,
});

// Formats completed-analysis timestamps for the report history table.
function formatDate(value?: string | null) {
  if (!value) return "—";

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) return "—";

  return new Intl.DateTimeFormat(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(date);
}

// Reports page: lists completed analyses and provides PDF download actions.
function Reports() {
  const [user, setUser] = useState<User | null>(auth.currentUser);
  const [jobs, setJobs] = useState<AnalysisHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [downloadingJobId, setDownloadingJobId] = useState<string | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
    });

    return unsubscribe;
  }, []);

  // API call: retrieves completed analysis history for the signed-in user.
  async function loadReports(showRefreshState = false) {
    try {
      if (showRefreshState) setRefreshing(true);
      else setLoading(true);

      setError("");

      const response = await fetch(
        `${API_BASE_URL}/api/analysis/`,
        {
          headers: {
            Accept: "application/json",
          },
        },
      );

      const data =
        (await response.json().catch(() => null)) as
          | AnalysisHistoryResponse
          | { detail?: string }
          | null;

      if (!response.ok) {
        throw new Error(
          typeof data?.detail === "string"
            ? data.detail
            : "Unable to load report history.",
        );
      }

      const currentUid = auth.currentUser?.uid;

      const completedJobs = (
        "jobs" in (data || {}) && Array.isArray(data?.jobs)
          ? data.jobs
          : []
      ).filter(
        (job) =>
          job.status === "completed" &&
          job.report_available &&
          (!job.owner_uid ||
            !currentUid ||
            job.owner_uid === currentUid),
      );

      setJobs(completedJobs);
    } catch (err) {
      console.error("[ImmunoXAI] Failed to load reports:", err);
      setError(
        err instanceof Error
          ? err.message
          : "Unable to load report history.",
      );
      setJobs([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }

  useEffect(() => {
    if (user) {
      void loadReports();
    } else {
      setJobs([]);
      setLoading(false);
    }
  }, [user]);

  // Downloads the PDF generated by the backend report endpoint for the selected job.
  async function downloadPdf(job: AnalysisHistoryItem) {
    try {
      setDownloadingJobId(job.job_id);
      setError("");

      const response = await fetch(
        `${API_BASE_URL}/api/analysis/${encodeURIComponent(
          job.job_id,
        )}/report`,
        {
          headers: {
            Accept: "application/pdf",
          },
        },
      );

      if (!response.ok) {
        const data = await response.json().catch(() => null);
        throw new Error(
          typeof data?.detail === "string"
            ? data.detail
            : "Failed to generate the PDF report.",
        );
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");

      anchor.href = url;
      anchor.download = `IMMUNO_XAI_Report_${job.job_id}.pdf`;
      document.body.appendChild(anchor);
      anchor.click();
      anchor.remove();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("[ImmunoXAI] PDF download failed:", err);
      setError(
        err instanceof Error
          ? err.message
          : "Unable to download the PDF report.",
      );
    } finally {
      setDownloadingJobId(null);
    }
  }

  return (
    <AppLayout
      title="Reports"
      subtitle="Download PDF reports from your completed analyses"
    >
      <div className="rounded-xl border border-border bg-card shadow-sm">
        <div className="flex flex-col gap-3 border-b border-border px-6 py-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold text-foreground">
              Generated Reports
            </h2>
            <p className="mt-1 text-xs text-muted-foreground">
              Each completed analysis has its own downloadable PDF report.
            </p>
          </div>

          <button
            type="button"
            onClick={() => void loadReports(true)}
            disabled={refreshing}
            className="inline-flex h-9 items-center gap-2 self-start rounded-lg border border-border bg-card px-3 text-xs font-medium text-foreground hover:bg-muted disabled:cursor-not-allowed disabled:opacity-60"
          >
            <RefreshCw
              className={`h-3.5 w-3.5 ${refreshing ? "animate-spin" : ""}`}
            />
            Refresh
          </button>
        </div>

        {error && (
          <div className="mx-6 mt-5 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">
            {error}
          </div>
        )}

        {loading ? (
          <div className="flex items-center justify-center gap-2 p-12 text-sm text-muted-foreground">
            <Loader2 className="h-4 w-4 animate-spin" />
            Loading reports...
          </div>
        ) : jobs.length === 0 ? (
          <div className="p-12 text-center">
            <FileText className="mx-auto h-9 w-9 text-muted-foreground" />
            <h3 className="mt-3 text-sm font-semibold text-foreground">
              No PDF reports yet
            </h3>
            <p className="mt-1 text-xs text-muted-foreground">
              Complete an analysis and its report will appear here.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-sm">
              <thead>
                <tr className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground">
                  <th className="px-6 py-3 font-medium">Dataset</th>
                  <th className="px-4 py-3 font-medium">Status</th>
                  <th className="px-4 py-3 font-medium">Completed</th>
                  <th className="px-6 py-3 text-right font-medium">
                    Report
                  </th>
                </tr>
              </thead>

              <tbody>
                {jobs.map((job) => (
                  <tr
                    key={job.job_id}
                    className="border-b border-border last:border-0"
                  >
                    <td className="px-6 py-4">
                      <div className="max-w-[420px] truncate font-medium text-foreground">
                        {job.dataset_name || job.job_id}
                      </div>
                      <div className="mt-0.5 text-xs text-muted-foreground">
                        {job.job_id}
                      </div>
                    </td>

                    <td className="px-4 py-4">
                      <span className="inline-flex rounded-full bg-[oklch(0.95_0.06_155)] px-2.5 py-0.5 text-xs font-medium text-[oklch(0.35_0.12_155)]">
                        Completed
                      </span>
                    </td>

                    <td className="px-4 py-4 text-xs text-muted-foreground">
                      {formatDate(
                        job.completed_at || job.started_at,
                      )}
                    </td>

                    <td className="px-6 py-4 text-right">
                      <button
                        type="button"
                        onClick={() => void downloadPdf(job)}
                        disabled={downloadingJobId === job.job_id}
                        className="inline-flex h-8 items-center gap-1.5 rounded-md bg-primary px-3 text-xs font-medium text-primary-foreground hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60"
                      >
                        {downloadingJobId === job.job_id ? (
                          <Loader2 className="h-3.5 w-3.5 animate-spin" />
                        ) : (
                          <Download className="h-3.5 w-3.5" />
                        )}
                        Download PDF
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </AppLayout>
  );
}
