from pathlib import Path

from app.pipeline.cluster_characterization import (
    run_cluster_characterization,
    ClusterCharacterizationConfig,
)


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent

ANALYSIS_DIR = (
    BASE_DIR
    / "analysis_data"
)

# Normalized expression matrix
EXPRESSION_PATH = (
    ANALYSIS_DIR
    / "normalization"
    / "normalized_log1p.npz"
)

# Cluster labels generated by clustering
CLUSTER_LABELS_PATH = (
    ANALYSIS_DIR
    / "clustering"
    / "cluster_labels.npy"
)

# Gene names generated/stored during normalization
GENES_PATH = (
    ANALYSIS_DIR
    / "normalization"
    / "genes.json"
)

# Cluster characterization output
OUTPUT_DIR = (
    ANALYSIS_DIR
    / "cluster_characterization"
)


# ============================================================
# TEST
# ============================================================

def main():

    print("=" * 70)
    print(
        "IMMUNO-XAI CLUSTER CHARACTERIZATION TEST"
    )
    print("=" * 70)

    print()
    print("INPUT FILES")
    print("-" * 70)

    print(
        "Expression:",
        EXPRESSION_PATH
    )

    print(
        "Cluster labels:",
        CLUSTER_LABELS_PATH
    )

    print(
        "Genes:",
        GENES_PATH
    )

    print(
        "Output:",
        OUTPUT_DIR
    )

    print()

    # --------------------------------------------------------
    # RUN CHARACTERIZATION
    # --------------------------------------------------------

    result = run_cluster_characterization(

        expression_path=EXPRESSION_PATH,

        cluster_labels_path=CLUSTER_LABELS_PATH,

        genes_path=GENES_PATH,

        output_dir=OUTPUT_DIR,

        config=ClusterCharacterizationConfig(

            top_n_genes=20,

            min_cells=5,

            min_expression_fraction=0.05,
        ),
    )

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    print()
    print(
        "Cells:",
        result["input_cells"]
    )

    print(
        "Genes:",
        result["input_genes"]
    )

    print(
        "Clusters:",
        result["n_clusters"]
    )

    print(
        "Top genes per cluster:",
        result["top_n_genes"]
    )

    print()
    print(
        "OUTPUT:"
    )

    print(
        result["output"]
    )

    # --------------------------------------------------------
    # LOAD OUTPUT
    # --------------------------------------------------------

    import json

    with open(
        result["output"],
        "r",
        encoding="utf-8",
    ) as f:

        data = json.load(f)

    # --------------------------------------------------------
    # PRINT TOP MARKERS
    # --------------------------------------------------------

    print()
    print(
        "TOP MARKERS"
    )
    print("-" * 70)

    for cluster_id, cluster_data in (
        data["clusters"].items()
    ):

        print()

        print(
            f"Cluster {cluster_id} "
            f"({cluster_data['n_cells']} cells)"
        )

        genes = [
            marker["gene"]
            for marker
            in cluster_data["top_markers"]
        ]

        print(
            "  ",
            ", ".join(genes)
        )

    # --------------------------------------------------------
    # COMPLETE
    # --------------------------------------------------------

    print()
    print("=" * 70)
    print(
        "CLUSTER CHARACTERIZATION TEST COMPLETE"
    )
    print("=" * 70)


if __name__ == "__main__":
    main()